---
- name: "Install basic shell packages"
  package: name={{ item }} state=present
  with_items:
    - ccze
    - curl
    - htop
    - tcpdump
    - telnet
    - traceroute
    - unzip
    - vim
    - wget
    - zip
  become: yes
