---
#- name: "Add apt config file"
#  copy: src=roles/system/files/apt.conf dest=/etc/apt/apt.conf
#  become: yes

- name: "Add local apt source mirror"
  copy:
    src: roles/system/files/sources_ubuntu_16_04_sh.list
    dest: /etc/apt/sources.list
  become: yes

- name: "apt update if needed"
  apt: update_cache=yes cache_valid_time=3600
